apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp-deployment
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
